name: Rollback Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to rollback (dev, qa, prod)'
        required: true
        default: 'dev'

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Rollback to previous deployment
        run: |
          aws eks update-kubeconfig --region ap-south-1 --name my-test-cluster
          kubectl rollout undo deployment/my-app-${{ github.event.inputs.environment }} -n default